### PR TITLE
Remove messy and unnecessary PS2 code.

### PR DESCRIPTION
**Pull request by Wolf3s**
Here is the compilation flags:
``` LIBFLUID_CPPFLAGS="-DFLUIDSYNTH_NOT_A_DLL -DFLUID_MUTEX_INIT" cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=${PS2DEV}/share/ps2dev.cmake" "-DCMAKE_INSTALL_PREFIX=${PS2SDK}/ports" -Denable=aufile=OFF -DBUILD_SHARED_LIBS=OFF -Denable-dbus=OFF -Denable-ipv6=OFF -Denable-jack=OFF -Denable-libinstpatch=OFF -Denable-libsndfile=OFF -Denable-midishare=OFF -Denable-network=OFF -Denable-oss=OFF -Denable-oss=OFF -Denable-dsound=OFF -Denable-wasapi=OFF -Denable-waveout=OFF -Denable-winmidi=OFF -Denable-pulseaudio=OFF -Denable-pipewire=OFF -Denable-readline=OFF -Denable-threads=OFF -Denable-openmp=OFF ```

### CODE REVIEW

**Comment by 7dog123** [comment]
Thanks man, I couldn't find the time to do any of this as I was busy with other stuff at home.

**Comment by Wolf3s** [comment]
> Thanks man, I couldn't find the time to do any of this as I was busy with other stuff at home.

No probs friend. I understand btw i´ve take a look a ps2prboom port and i could say that it doesn´t load any wad and there are some unecessary code aswell.

**Comment by Wolf3s** [comment]
but in less scale.

**Comment by 7dog123** [comment]
> No probs friend. I understand btw i´ve take a look a ps2prboom port and i could say that it doesn´t load any wad and there are some unecessary code aswell.

I know. But you can help me with the ps2prboom port if you want to that is.

**Comment by Wolf3s** [comment]
> > No probs friend. I understand btw i´ve take a look a ps2prboom port and i could say that it doesn´t load any wad and there are some unecessary code aswell.
> 
> I know. But you can help me with the ps2prboom port if you want to that is.

I will try to help ya, But i would prefer to switch to prboom-plus codebase. Also did you has a showcase video?

**Comment by 7dog123** [comment]
> > > No probs friend. I understand btw i´ve take a look a ps2prboom port and i could say that it doesn´t load any wad and there are some unecessary code aswell.
> > 
> > 
> > I know. But you can help me with the ps2prboom port if you want to that is.
> 
> I will try to help ya, But i would prefer to switch to prboom-plus codebase. Also did you has a showcase video?

Not really. I've never had the chance to make one. Plus the reason why I'm using the original prboom as a test before trying to do prboom-plus and you can help with it when ever you can. There's literally no rush on it.

**Comment by Wolf3s** [comment]
> Owner

i added a pr but i will try to see prboom-plus port.

**Pull request merged**
